---
svn_base_url: 'svn+ssh://repo.freebsd.org/ports/head'
ports_dir: '~/Org/freebsd/ports'
dev_dir: '~/Code/ports'
ports:
  - databases/puppetdb5
  - databases/puppetdb6
  - databases/puppetdb-terminus5
  - databases/puppetdb-terminus6
  - sysutils/facter
  - sysutils/puppet5
  - sysutils/puppet6
  - sysutils/puppetserver5
  - sysutils/puppetserver6
  - sysutils/rubygem-facter
